version: "3"
services:
    php-fpm:
#        image: admin-php-fpm
#        command: --allow-to-run-as-root --user root:root
#        command:
#            - bash
#            - -c
#            - |
#                sh /usr/share/nginx/html/start_gameloop.sh
#                php-fpm
        image: ${PHP}
        command:
            /bin/bash -c "chown -R www-data:www-data /usr/share/nginx/html/ &&
            php-fpm"
        restart: unless-stopped
        cap_add:
            - SYS_PTRACE
        links:
            - mysql
            - redis
        volumes:
            - "../:/usr/share/nginx/html"    # 需要与 nginx 配置的 root 目录一致，或者在 nginx.conf 中 fastcgi_param SCRIPT_FILENAME 指定为 container 中的路径
            - "./php/conf.d/security.ini:/usr/local/etc/php/conf.d/security.ini" #映射ini文件
            - "/etc/localtime:/etc/localtime"

    nginx:
        image: ${NGINX}
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
        links:
            - php-fpm
        volumes:
            - "./nginx/conf.d:/etc/nginx/conf.d:ro"
            - "../:/usr/share/nginx/html"
            - "./nginx/log:/var/log/nginx"
            - "/etc/localtime:/etc/localtime"

    mysql:
        image: ${MYSQL}
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}    #root用户的密码
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - "./mysql/data:/var/lib/mysql:rw"
            - "./mysql/setup:/setup"
            - "./mysql/backup:/backup"
            - "/etc/localtime:/etc/localtime"
            - "./mysql/conf.d:/etc/mysql/conf.d"

    redis:
        image: ${REDIS}
        restart: unless-stopped
        ports:
            - ${REDIS_PORT}:6379
        command: redis-server /usr/local/etc/redis/redis.conf
        environment:
            - TZ=${TIMEZONE}
        volumes:
            - "./redis/conf:/usr/local/etc/redis:ro"
            - "./redis/log:/var/log/redis:rw"
            - "./redis/data:/data:rw"


